### ISSUE TITLE
Where to download the Math23K dataset?

### ISSUE THREAD

**Issue by WSTC2007** [MiuLab/E2EMathSolver#1]
Hi, I don’t know where to download the Math23K dataset. Can you can me? Thanks!

**Comment by jellying** [comment]
Hi, I have the same question. Where can I download the Math23k? Have you solved it?

**Comment by WSTC2007** [comment]
> Hi, I have the same question. Where can I download the Math23k? Have you solved it?

I sent an email to the author of the paper, and he sent the data set to me amicably.

**Comment by jellying** [comment]
Oh, thanks for your reply.

**Comment by elhalag93** [comment]
i need this data set ,can you send it to me?

**Comment by Sologala** [comment]
excuse me ~, could you please share the MATH23K dataset to me ?  Thx!

**Comment by falaktheoptimist** [comment]
https://github.com/ShichaoSun/math_seq2tree/blob/master/data/Math_23K.json

**Comment by libertywing** [comment]
https://ai.tencent.com/ailab/nlp/dialogue/#Dataset

**Comment by Sologala** [comment]
@libertywing Li Great Thanks!  though I have devoted in computer vision.
